### ISSUE TITLE
Add a server as an executable

### ISSUE THREAD

**Issue by notpushkin** [dcposch/webtorrent-remote#1]
Like in, `$ webtorrent-server -p 8000`. It can be JSON-RPC, or whatever. Just to establish a standard way to communicate with webtorrent-remote from other processes; those who want can just set up their own communication channel like they would do now. What do you think?

I'm working on a Python client right now, by the way.

**Comment by dcposch** [comment]
Sorry, seeing this just now!

If there was a command-line `webtorrent-server`, what would you use it for?

Currently, the two uses cases I know for `webtorrent-remote` are:

* **Brave**

  Brave is an experimental web browser, and I recently did a project adding torrent support, so that you can paste a magnet link directly into the URL bar. There, there's a webtorrent-remote client is every magnet link tab and a single server in the main browser process. (See [this page](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md) for the diff between browser and renderer processes.)

* **WebTorrent Desktop**

  I haven't updated WebTorrent Desktop to use `webtorrent-remote` yet, but I plan to. That app was the first place I needed to run WebTorrent in one process and control it from another. [I did that a few months ago](https://github.com/feross/webtorrent-desktop/pull/299), in a jankier, one-off way, and `webtorrent-remote` is my way to make that more legit and extract it into its own module.

--

What both of those have in common: they're packaged apps that happen to run multiple processes under the hood.

I'm curious to hear your use case.

**Comment by dcposch** [comment]
BTW an HTTP server is not ideal. You want a full duplex socket.

--

I'm guessing you want to write a Python app that uses WebTorrent?

You could try making a small Node server that creates a `WebTorrentRemoteServer`, listens for a TCP connection. It interprets each line received as JSON and passes it to `server.receive(...)`. In `send()`, it just writes JSON plus a newline out to that same socket.

You probably wouldn't even need reconnect logic as long as both processes (Python client and Node server) are on the same computer.

**Comment by dcposch** [comment]
Closing. Feel free to re-open if you have a specific use in mind that would benefit from a command line, standalone `webtorrent-remote`.
